const a = 100;

try {
    console.log('try')
} catch (error) {
    console.log('error', error)
} finally {
    console.log('finally')
}